spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dangun_market?serverTimezone=Asia/Seoul
    username: root
    password: root1234!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 100

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

cloud:
  aws:
    s3:
      bucket: dangun-bucket
    credentials:
      access-key: AKIAURW3G6NSUHKHQC5X
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
